### ISSUE TITLE
LillaOst is TOO awesome

### ISSUE THREAD

**Issue by Napo2k** [jcbellido/LillaOst-Feedback#2]
Seriously, it's going to make me go insane. Please STAHP

Lorem ipsum flonder manguer

Not everyone will use LillaOst
Especially if they are not parents
Very much my case I might add
Even then I will gladly test it

Random thought: 
Granting different levels of permissions?
Owners of the "babies", babysitter, etc.
Not sure if that is something that could be considered for the future
Nonetheless that's an idea.
Another one:
Goals? In the same vein that Fitbit has goals? Maybe not so "strict"
It would be interesting, having the goal of "first steps when the baby is 2 months" or whatever
Verifying all of this with a medical professional, of course

Either way
You reckon you can get this issue automation going?
Obscure the future of LillaOst is
Unknown its paths

Pater

**Comment by jcbellido** [comment]
aww, you cute <3
